export { authEmailApi } from './AuthEmailApi';
export { oauth2Methods, AuthOauth2BaseApi } from '@/api/auth/AuthOauth2BaseApi';
export { authGithubApi } from './AuthGithubApi';
export { authVkApi } from './AuthVkApi';
export { authTelegramApi } from './AuthTelegramApi';
export { authGoogleApi, authPhysicsApi } from './AuthPhysicsApi';
export { authLkmsuApi } from './AuthLkmsuApi';
export { authYandexApi, authMymsuApi } from './AuthMymsuApi';
export { authGroupApi, GroupInfo } from './AuthGroupApi';
export { authScopeApi } from './AuthScopeApi';
export { authUserApi, UserInfo } from './AuthUserApi';
export { userSessionApi, MySessionInfo, AuthMethod, SessionInfo } from './UserSessionApi';
