name: Тесты и раскатка на Pull Request (остановка)

on:
  pull_request:
    types: [closed]

jobs:
  stop-deployment-dev:
    name: Останавливаем dev среду
    runs-on: ubuntu-latest
    environment:
      name: development-pr-${{ github.event.pull_request.number }}
    steps:
      - name: Stop deployment
        run: |
          curl -X 'POST' \
            'https://ci.dev.profcomff.com/pr_stop' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: ${{ secrets.CI_DYAKOVSPACE_MSK_TOKEN }}' \
            -d '{
              "repo_url": "${{ github.repository }}",
              "git_ref": "${{ github.ref }}"
            }'
